### ISSUE TITLE
#6 git compatibility

### ISSUE THREAD

**Issue by GeunsSv** [I8C/sonar-flow-plugin#8] opened 2016-10-21 08:16 UTC
When a .git folder is present in the package folder an error occurs, preventing a successfull check of the package.

**Comment by dewanst** [comment] 2017-03-14 19:04
@GeunsSv @Samuelvdc Could you reproduce the error and share the error. I'm not getting an error...

(I do get an error from the SCM plugin when changes aren't comitted, but this is normal behaviour)

**Comment by GeunsSv** [comment] 2017-03-28 12:07
@dewanst @Samuelvdc 
As requested the error in the text file. I Also added my package where i encountered the issue in. 
The error only occurs when the .git folder is present.
The .git folder was present for another project (The eclipse plugin project for the document creator if i remember correctly).  
[Acme.zip](https://github.com/I8C/sonar-flow-plugin/files/875538/Acme.zip)
[fault.txt](https://github.com/I8C/sonar-flow-plugin/files/875539/fault.txt)

**Comment by Samuelvdc** [comment] 2017-08-09 08:49
Closing, doesn't appear to be an issue with the plugin. Is caused by SCM plugin

**Closed by Samuelvdc** 2017-08-09 08:49 UTC
